services:
  api:
    build:
      context: .
      args:
        requirements_file: ./requirements.txt
    env_file:
      - .env
    stdin_open: true
    tty: true
    command: sh -c "uvicorn app.main:app --reload --port=8000 --host=0.0.0.0"
    volumes:
      - .:/app
      - ./data:/data
    ports:
      - 8000:8000
    networks:
      - app-network

  mongo:
    image: mongo
    restart: always
    env_file:
      - .env
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    volumes:
      - mongo_data:/data/db
    networks:
      - app-network

  mongo-express:
    image: mongo-express
    restart: always
    env_file:
      - .env
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      ME_CONFIG_MONGODB_URL: mongodb://${MONGO_INITDB_ROOT_USERNAME}:${MONGO_INITDB_ROOT_PASSWORD}@mongo:27017/?authSource=admin&retryWrites=true&w=majority
      ME_CONFIG_BASICAUTH_USERNAME: ${MONGOEXPRESS_LOGIN}
      ME_CONFIG_BASICAUTH_PASSWORD: ${MONGOEXPRESS_PASSWORD}
    volumes:
      - mongo_data:/data/db
    networks:
      - app-network
    links:
      - mongo

networks:
  app-network:
    driver: bridge

volumes:
  mongo_data: